/**
 * Íconos de SAFIC: Material Symbols Rounded (prefijo `sym_r_` en Quasar).
 * Todo ítem del menú lateral DEBE tener ícono. Usa estas constantes en vez de
 * escribir el nombre a mano para que el catálogo quede en un solo lugar.
 * Catálogo: https://fonts.google.com/icons?icon.style=Rounded
 */
export const ICONOS = {
  inicio: 'sym_r_space_dashboard',
  unidades: 'sym_r_apartment',
  bloques: 'sym_r_domain',
  residentes: 'sym_r_groups',
  finanzas: 'sym_r_account_balance_wallet',
  cuotas: 'sym_r_receipt_long',
  cobroCuotas: 'sym_r_request_quote',
  pagos: 'sym_r_payments',
  proveedores: 'sym_r_local_shipping',
  reservas: 'sym_r_event_available',
  amenidades: 'sym_r_pool',
  garita: 'sym_r_shield_person',
  comunicacion: 'sym_r_campaign',
  asambleas: 'sym_r_how_to_vote',
  usuarios: 'sym_r_manage_accounts',
  apariencia: 'sym_r_palette',
  configuracion: 'sym_r_settings',
  plataforma: 'sym_r_admin_panel_settings',
  condominio: 'sym_r_location_city',
  cambiar: 'sym_r_swap_horiz',
  salir: 'sym_r_logout',
  agregar: 'sym_r_add',
  menu: 'sym_r_menu',
  buscar: 'sym_r_search',
  refrescar: 'sym_r_refresh',
  bloqueado: 'sym_r_lock',
  vacio: 'sym_r_inbox',
  volver: 'sym_r_chevron_left',
  info: 'sym_r_info',
  importar: 'sym_r_upload',
  descargar: 'sym_r_download',
  archivo: 'sym_r_upload_file',
  correcto: 'sym_r_check_circle',
  alerta: 'sym_r_error',
  siguiente: 'sym_r_chevron_right',
  sinResultados: 'sym_r_search_off',
  // Módulos y pantallas (mismos nombres que en los mockups)
  resumen: 'sym_r_dashboard',
  pagosPorAprobar: 'sym_r_fact_check',
  conciliacion: 'sym_r_account_balance',
  cuentasPorPagar: 'sym_r_payments',
  agenda: 'sym_r_calendar_month',
  areasReglas: 'sym_r_rule',
  anuncios: 'sym_r_campaign',
  incidencias: 'sym_r_report',
  prepararAsamblea: 'sym_r_edit_calendar',
  mesaAsamblea: 'sym_r_groups',
  datosCondominio: 'sym_r_domain',
  roles: 'sym_r_admin_panel_settings',
  suscripcion: 'sym_r_card_membership',
  cobranza: 'sym_r_paid',
  condominios: 'sym_r_location_city',
  planes: 'sym_r_view_module',
  catalogo: 'sym_r_category',
  menuSistema: 'sym_r_menu_open',
  miHogar: 'sym_r_home',
  visitas: 'sym_r_qr_code_2',
  asamblea: 'sym_r_how_to_vote',
  directorio: 'sym_r_contacts',
  llamar: 'sym_r_call',
  garitaApp: 'sym_r_badge',
  reservasHoy: 'sym_r_event',
  pagosApp: 'sym_r_payments',
  vistaPrevia: 'sym_r_visibility',
} as const;

export type NombreIcono = keyof typeof ICONOS;
export type Icono = (typeof ICONOS)[NombreIcono];
